/** 백엔드 `ApiErrorCodes`와 동일한 문자열 (hid-amico-server 계약) */
export const API_ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  USER_INVALID_ID: "USER_INVALID_ID",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_VALIDATION_REQUIRED: "USER_VALIDATION_REQUIRED",
  USER_ID_DUPLICATE: "USER_ID_DUPLICATE",
  ACCESS_LOG_NOT_FOUND: "ACCESS_LOG_NOT_FOUND",
  /** 클라이언트 전용 */
  UNKNOWN: "UNKNOWN",
  CLIENT_NETWORK_ERROR: "CLIENT_NETWORK_ERROR",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
